name: vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Debug SonarQube configuration
        run: |
          echo "=== SonarQube Configuration ==="
          echo "SONAR_URL: ${{ secrets.SONAR_URL }}"
          echo "SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}"
          echo "SONAR_PROJECT_KEY from secret: ${{ secrets.SONAR_PROJECT_KEY }}"
          echo "Using hardcoded project key: vprofile-actions4u"
          echo "SONAR_TOKEN exists: $([ ! -z '${{ secrets.SONAR_TOKEN }}' ] && echo 'YES' || echo 'NO')"

      - name: Test SonarCloud API access
        run: |
          echo "Testing SonarCloud API access with token..."
          # Test basic API access
          curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/system/status" | head -20
          echo ""

      - name: Check if project exists
        run: |
          echo "Checking if project vprofile-actions4u exists in organization ${{ secrets.SONAR_ORGANIZATION }}..."
          response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/projects/search?projects=vprofile-actions4u")
          echo "API Response: $response"
          
          if echo "$response" | grep -q '"total":1'; then
            echo "✅ Project vprofile-actions4u exists"
          else
            echo "❌ Project vprofile-actions4u does not exist or cannot be accessed"
            echo "Please manually create the project in SonarCloud:"
            echo "1. Go to https://sonarcloud.io"
            echo "2. Navigate to your organization: ${{ secrets.SONAR_ORGANIZATION }}"
            echo "3. Click 'Add new project'"
            echo "4. Create project with key: vprofile-actions4u"
            echo "5. Name: VProfile GitHub Actions"
            exit 1
          fi

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Run tests with coverage
        run: |
          mvn clean test jacoco:report checkstyle:checkstyle
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan with explicit project key
        run: |
          echo "Running SonarQube analysis with project key: vprofile-actions4u"
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=vprofile-actions4u \
            -Dsonar.projectName="VProfile GitHub Actions" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.java.test.binaries=target/test-classes
        env:
          SONAR_SCANNER_OPTS: -Xmx1024m

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/checkstyle-result.xml
            target/site/jacoco/
          retention-days: 7