name: vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Debug SonarQube configuration
        run: |
          echo "=== SonarQube Configuration ==="
          echo "SONAR_URL: ${{ secrets.SONAR_URL }}"
          echo "SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}"
          echo "SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
          echo "SONAR_TOKEN length: ${#SECRETS.SONAR_TOKEN} characters"
          
          # Validate required secrets
          if [[ -z "${{ secrets.SONAR_ORGANIZATION }}" ]]; then
            echo "❌ ERROR: SONAR_ORGANIZATION is empty!"
            exit 1
          fi
          if [[ -z "${{ secrets.SONAR_PROJECT_KEY }}" ]]; then
            echo "❌ ERROR: SONAR_PROJECT_KEY is empty!"
            exit 1
          fi

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Run tests with coverage
        run: |
          mvn clean test jacoco:report checkstyle:checkstyle
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN

      - name: Verify coverage reports
        run: |
          echo "=== Verifying Analysis Files ==="
          ls -la target/ || echo "target directory not found"
          [ -f target/jacoco.exec ] && echo "✅ jacoco.exec exists" || echo "❌ jacoco.exec missing"
          [ -d target/surefire-reports ] && echo "✅ surefire-reports exists" || echo "❌ surefire-reports missing"

      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.projectName="VProfile Application" \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.coveragePlugin=jacoco \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.java.test.binaries=target/test-classes
        env:
          SONAR_SCANNER_OPTS: -Xmx1024m

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/checkstyle-result.xml
            target/site/jacoco/
          retention-days: 7